vars: org/clulab/aske_automates/grammars/vars.yml

rules:


  ####VALUES####


  - name: var_equals_val
    label: ParameterSetting
    priority: ${priority}
    type: token
    #action: variableArguments
    example: "EORATIO is defined as the maximum Kcs at LAI = 6.0"
    pattern: |
      # @trigger:Concept "=" @Value:Value
      @variable:Variable (?<trigger> [word="="]) @value:Value


  - name: var-vary_between
    label: ParameterSetting
    priority: ${priority}
    type: dependency
    #action: variableArguments
    example: "The value of Kcbmax was varied between 0.9 and 1.4"
    pattern: |
      trigger = [lemma='vary']
      variable:Variable = nsubjpass nmod_of
      value:Interval = nmod_between

  - name: var_hard-coded
    label: ParameterSetting
    priority: ${priority}
    type: dependency
    example: "EORATIO for maize simulations was hard-coded to 1.0 within DSSAT-CSM."
    pattern: |
      trigger = [word=/(?i)^hard-coded/]
      variable:Concept = nsubj
      value: Concept = /nmod_to/


  - name: var-noun_of
    label: ParameterSetting
    priority: ${priority}
    type: token
    example: "If E and T data are unavailable, values of SKc from 0.5 to 0.7 are recommended."
    pattern: |
      (?<trigger> [lemma="value"]) of @variable:Variable from @valueLeast:Value to @valueMost:Value
