vars: org/clulab/aske_automates/grammars/vars.yml

rules:


  ####VALUES####


  - name: var_equals_val
    label: ParameterSetting
    priority: ${priority}
    type: token
    #action: variableArguments
    example: "EORATIO is defined as the maximum Kcs at LAI = 6.0"
    pattern: |
      # @trigger:Concept "=" @Value:Value
      @variable:Variable (?<trigger> [word="="]) @value:Value


  # todo: unify the priorities
  # todo: try to get everything in a certain file to have the same priority, pass the priority in as a variable
  # todo: so then you would have: `priority: ${priority}`
  - name: var-vary_between
    label: ParameterSetting
    priority: ${priority}
    type: dependency
    #action: variableArguments
    example: "The value of Kcbmax was varied between 0.9 and 1.4"
    pattern: |
      trigger = [lemma='vary']
      variable:Variable = nsubjpass nmod_of
      value:Interval = nmod_between
