vars: org/clulab/aske_automates/grammars/vars.yml

rules:

  - name: value_entity
    label: Value
    priority: ${priority}
    type: token
    #action: identifierArguments
    example: "EORATIO is defined as the maximum Kcs at LAI = 6.0"
    pattern: |
      [entity = /NUMBER|PERCENT/]
      # note: got rid of tag = /CD/ part to address the patterns like "12 millions" ("millions" is captured as number, but does not have tag = CD)

  - name: mult_value
    label: Value
    priority: ${priority}
    type: token
    #action: identifierArguments
    example: "EORATIO is defined as the maximum Kcs at LAI = 6.0"
    pattern: |
      [entity = /NUMBER|PERCENT/ & tag = /CD/] [word = "x"] [entity = /NUMBER|PERCENT/ & tag = /CD/]
      |
      [entity = /NUMBER|PERCENT/]+
      # note: second rule added to address cases like "12 milions"



