vars: org/clulab/aske_automates/grammars/vars.yml

rules:

  - name: value_entity
    label: Value
    priority: ${priority}
    type: token
    example: "EORATIO is defined as the maximum Kcs at LAI = 6.0"
    pattern: |
      [entity = /NUMBER|PERCENT/ & tag = /CD/]

  - name: mult_value
    label: Value
    priority: ${priority}
    type: token
    example: "EORATIO is defined as the maximum Kcs at LAI = 6.0"
    pattern: |
      [entity = /NUMBER|PERCENT/ & tag = /CD/] [word = "x"] [entity = /NUMBER|PERCENT/ & tag = /CD/]

  - name: compound_value
    label: Value
    priority: ${compoundPriority}
    type: token
    example: "63 million of cats"
    pattern: |
      @Value @Value



